#First Yaml cloudformation example
AWSTemplateFormatVersion: 2010-09-09
Description: My First enviroment

Resources:
  WebappInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-02f3416038bdb17fb
      InstanceType: t2.micro
      KeyName: Chaves-virginia
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:  !Join ["-", [webapp-security-group, dev]]
      GroupDescription: "Permitir HTTP/HTTPS e tambem a entrada SSH"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol:
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          




